"""Local profile storage for device and locale configuration.

Profiles contain identifiers supplied or generated by the caller. They are
stored outside the repository and are never read from captures.
"""

from __future__ import annotations

import locale
import os
import secrets
from pathlib import Path
from typing import Any

try:  # Python 3.11+
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - Python 3.10 fallback
    import tomli as tomllib  # type: ignore[no-redef]

from .config import DeviceProfile, SDKConfig
from .cache import JsonCache


def _default_locale() -> tuple[str, str]:
    value = locale.getlocale()[0] or "en_US"
    language, _, region = value.replace("-", "_").partition("_")
    if language in {"C", "POSIX"}:
        language = "en"
    region = region.upper() or "US"
    return region, f"{language or 'en'}-{region}"


def _synthetic_id(prefix: str) -> str:
    return f"{prefix}-{secrets.token_hex(12)}"


class ProfileStore:
    """Read and write TOML profiles under the user's config directory."""

    def __init__(self, root: Path | None = None):
        if root is None:
            root = Path(os.getenv("CLIPCRAFT_CONFIG_HOME", ""))
            if not root:
                root = Path(os.getenv("XDG_CONFIG_HOME", Path.home() / ".config"))
            root = root / "clipcraft-labs" / "capcut"
        self.root = root
        self.profiles_dir = root / "profiles"

    @property
    def default_path(self) -> Path:
        return self.profiles_dir / "default.toml"

    @property
    def cache(self) -> JsonCache:
        return JsonCache(self.root / "cache")

    def ensure_default(self) -> Path:
        if not self.default_path.exists():
            self.save("default", self.default_profile())
        return self.default_path

    def default_profile(self) -> dict[str, Any]:
        region, language = _default_locale()
        return {
            "profile": {"name": "default", "mode": "offline"},
            "device": {
                "device_id": _synthetic_id("local-device"),
                "iid": _synthetic_id("local-install"),
            },
            "locale": {"region": region, "language": language},
        }

    def load(self, name: str = "default") -> dict[str, Any]:
        path = self.profiles_dir / f"{name}.toml"
        if name == "default" and not path.exists():
            self.ensure_default()
        if not path.exists():
            raise FileNotFoundError(f"Profile not found: {name}")
        with path.open("rb") as handle:
            return tomllib.load(handle)

    def save(self, name: str, values: dict[str, Any]) -> Path:
        self.profiles_dir.mkdir(mode=0o700, parents=True, exist_ok=True)
        path = self.profiles_dir / f"{name}.toml"
        path.write_text(_dump_toml(values), encoding="utf-8")
        path.chmod(0o600)
        return path

    def names(self) -> list[str]:
        self.ensure_default()
        return sorted(path.stem for path in self.profiles_dir.glob("*.toml"))

    def sdk_config(self, name: str = "default", *, live: bool | None = None) -> SDKConfig:
        values = self.load(name)
        device = values.get("device", {})
        locale_values = values.get("locale", {})
        profile = values.get("profile", {})
        return SDKConfig(
            device=DeviceProfile(
                str(device.get("device_id", "")),
                str(device.get("iid", "")),
            ),
            region=str(locale_values.get("region", "US")),
            language=str(locale_values.get("language", "en-US")),
            mode="live" if live is True else str(profile.get("mode", "offline")),
        )


def config_from_environment(store: ProfileStore | None = None) -> SDKConfig:
    """Resolve environment overrides over the default local profile."""

    store = store or ProfileStore()
    values = store.load(os.getenv("CAPCUT_PROFILE", "default"))
    device = values.setdefault("device", {})
    locale_values = values.setdefault("locale", {})
    profile = values.setdefault("profile", {})
    device["device_id"] = os.getenv("CAPCUT_DEVICE_ID", device.get("device_id", ""))
    device["iid"] = os.getenv("CAPCUT_IID", device.get("iid", ""))
    locale_values["region"] = os.getenv("CAPCUT_REGION", locale_values.get("region", "US"))
    locale_values["language"] = os.getenv("CAPCUT_LANGUAGE", locale_values.get("language", "en-US"))
    profile["mode"] = os.getenv("CAPCUT_MODE", profile.get("mode", "offline"))
    return SDKConfig(
        device=DeviceProfile(str(device["device_id"]), str(device["iid"])),
        region=str(locale_values["region"]),
        language=str(locale_values["language"]),
        mode=str(profile["mode"]),
    )


def _dump_toml(values: dict[str, Any]) -> str:
    lines: list[str] = []
    for section, entries in values.items():
        if not isinstance(entries, dict):
            continue
        lines.append(f"[{section}]")
        for key, value in entries.items():
            if isinstance(value, bool):
                rendered = "true" if value else "false"
            else:
                rendered = '"' + str(value).replace('\\', '\\\\').replace('"', '\\"') + '"'
            lines.append(f"{key} = {rendered}")
        lines.append("")
    return "\n".join(lines)
